name: build
on:
  workflow_dispatch:

jobs:
  Arm64:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/checkout@v3
        with:
          repository: "eko5624/mpv-android-test"
          ref: "upstream-vk-patch"
          fetch-depth: 0
          
      #- name: Install dependencies
      #  run: |
      #     sudo apt-get update
      #     sudo apt-get install -y autoconf pkg-config libtool ninja-build python3-pip \
      #     python3-setuptools unzip openssl ca-certificates nasm
      #     sudo pip3 install meson ninja mako  
      
      - name: set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        
      - name: remove default ndk  
        run: sdkmanager --uninstall "ndk;25.1.8937393"
             rm -rf sdkmanager /usr/local/lib/android/sdk/ndk-bundle
             
      #- name: Install NDK
      #  run: sdkmanager "ndk;23.2.8568313"
        
      - name: download-deps
        working-directory: ./buildscripts
        run: |
          ./download.sh
          
      - name: build-apk
        working-directory: ./buildscripts
        run:  |
          ./buildall.sh --clean
          ./buildall.sh -n
      - name: relocate apks
        run: |
          mkdir -p app/build/outputs/apk/release
          cp "./app/build/outputs/apk/default/release/app-default-universal-release-unsigned.apk"  app/build/outputs/apk/release/mpv-default.apk
          cp "./app/build/outputs/apk/api29/release/app-api29-universal-release-unsigned.apk" app/build/outputs/apk/release/mpv-api29.apk
          cp "./app/build/outputs/apk/api29/debug/app-api29-universal-debug.apk" app/build/outputs/apk/release/mpv-api29-debug.apk
          cp "./app/build/outputs/apk/default/debug/app-default-universal-debug.apk" app/build/outputs/apk/release/mpv-default-debug.apk
      - name: Sign APK
        uses: ilharp/sign-android-release@v1.0.2 # Or use @nightly
        id: sign_app
        with:
          releaseDir: app/build/outputs/apk/release
          signingKey: ${{ secrets.ANDROID_SIGNING_KEY }}
          keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          buildToolsVersion: 33.0.0
      - name : upload APKs
        uses: actions/upload-artifact@v2
        with:
          name: Arm-Build
          path: |
                app/build/outputs/apk/release/mpv-default-signed.apk
                app/build/outputs/apk/release/mpv-api29-signed.apk
                app/build/outputs/apk/release/mpv-default-debug-signed.apk
                app/build/outputs/apk/release/mpv-api29-debug-signed.apk
